version: 2
jobs:
  build:
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: yarn build
      - deploy:
          command: |
            cd dist
            yarn publish

workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - Globals